name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - name: Cache Coursier
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v3.0.4
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Check format
        run: sbt headerCheck test:headerCheck scalafmtCheckAll
      - name: Run tests
        run: sbt -J-Xmx2G -J-XX:+UseG1GC +compile observe_modelJVM/test observe_modelJS/test observe_engine/test observe_server/test observe_web_server/test observe_web_client/test
